CREATE SCHEMA REPORT;
CREATE TABLE REPORT.OPENJPA_SEQUENCE_TABLE (ID bigint generated by default as identity not null primary key, SEQUENCE_VALUE bigint not null);

CREATE TABLE REPORT.T_INCIDENT (
    INCIDENT_ID bigint generated by default as identity not null primary key,
    INCIDENT_REF varchar(55),
    INCIDENT_DATE date,
    GIVEN_NAME varchar(35),
    FAMILY_NAME varchar(35),
    SUMMARY varchar(35),
    DETAILS varchar(255),
    EMAIL varchar(60),
    PHONE varchar(35),
    CREATION_DATE date,
    CREATION_USER varchar(255)
);
INSERT INTO REPORT.T_INCIDENT (INCIDENT_REF,INCIDENT_DATE,GIVEN_NAME,FAMILY_NAME,SUMMARY,DETAILS,EMAIL,PHONE) VALUES ('001','2016-03-21','Charles','Moulliard','Incident Course-001','This is a report incident for course-001','cmoulliard@redhat.com','+111 10 20 300');
INSERT INTO REPORT.T_INCIDENT (INCIDENT_REF,INCIDENT_DATE,GIVEN_NAME,FAMILY_NAME,SUMMARY,DETAILS,EMAIL,PHONE) VALUES ('002','2016-03-22','Jeff','Delong','Incident Course-002','This is a report incident for course-002','jdelong@redhat.com','+111 10 20 300');
INSERT INTO REPORT.T_INCIDENT (INCIDENT_REF,INCIDENT_DATE,GIVEN_NAME,FAMILY_NAME,SUMMARY,DETAILS,EMAIL,PHONE) VALUES ('003','2016-03-23','Jeff','Bride','Incident Course-003','This is a report incident for course-003','jbride@redhat.com','+111 10 20 300');
INSERT INTO REPORT.T_INCIDENT (INCIDENT_REF,INCIDENT_DATE,GIVEN_NAME,FAMILY_NAME,SUMMARY,DETAILS,EMAIL,PHONE) VALUES ('004','2016-03-24','Charles','Moulliard','Incident Course-004','This is a report incident for course-004','cmoulliard@redhat.com','+111 10 20 300');